# Generated by Django 5.2.11 on 2026-04-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_icon_class_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Liter (L)'), ('ml', 'Milliliter (ml)'), ('pc', 'Piece (pc)'), ('dz', 'Dozen (dz)'), ('pkt', 'Packet (pkt)')], default='kg', max_length=10),
        ),
    ]
